### ISSUE TITLE
Profile app speed issues.

### ISSUE THREAD

**Issue by connorlay** [KnitGrid/knitgrid-android#15]
Our Android app has a significant slowdown when launching and saving patterns. We suspect this could be related to how we are using Realm. Further investigation is required.

Acceptance criteria:
- Discover what exactly is causing our app to lag on startup.
- Discover what exactly is causing our app to lag on pattern creation.
- Come up with a plan of attack for solving this issue (likely to create a new ticket).

**Comment by Magisus** [comment]
The profiling tools were rather non-specific, but scaling up the size of patterns causes save time to go up significantly, so I'm still going to point my finger at Realm. I recommend we rip it out and put in vanilla SQLite.
