### ISSUE TITLE
Upgrade to Realm 1.0

### ISSUE THREAD

**Issue by connorlay** [KnitGrid/knitgrid-android#16]
Realm recently hit 1.0! We need to upgrade our app to use the new, stable version of Realm.

Acceptance criteria:
- The app successfully runs on Realm 1.0.

**Comment by Magisus** [comment]
This was fairly simple, only one method we were using was deprecated. However, it didn't seem to fix the slowness at all. Saving a 5x30 pattern (a fairly standard size) takes upwards of 10 seconds on my emulator.

**Comment by connorlay** [comment]
Hmmm ok do you want to open a PR for the realm bump? Or leave it in a feature branch?

**Comment by Magisus** [comment]
I think we can just leave it in a feature branch, since we're going to rip out Realm anyway.
